import { Inter } from "next/font/google";
import "../globals.css";
import "@/styles/css/bootstrap.min.css";
import "@/styles/css/bootstrap4-toggle.min.css";
import "@/styles/css/bootstrap-select.min.css";
import "@/styles/css/bootstrap-slider.min.css";
import "@/styles/css/dataTables.bootstrap4.min.css";
import "@/styles/css/dropzone.css";
// import "@/styles/css/font.css";
import "@/styles/css/feather.css";
import "@/styles/css/font-awesome.min.css";
// import "@/styles/css/lc_lightbox.css";
import "@/styles/css/magnific-popup.min.css";
import "@/styles/css/m-custom-scrollbar.min.css";
import "@/styles/css/owl.carousel.min.css";
import "@/styles/css/slick.min.css";
import "@/styles/css/slick-theme.css";
import "@/styles/css/style.css";
import Script from "next/script";
import GuestHeader from "@/components/GuestHeader";
import GuestFooter from "@/components/GuestFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="page-wraper">
          <GuestHeader />
          <div className="page-content">{children}</div>

          <GuestFooter />
        </div>
        <Script src="/js/jquery-3.6.0.min.js" />
        <Script src="/js/popper.min.js" />
        <Script src="/js/bootstrap.min.js" />
        <Script src="/js/bootstrap-select.min.js" />
        <Script src="/js/jquery.bootstrap-touchspin.js" />
        <Script src="/js/magnific-popup.min.js" />
        <Script src="/js/waypoints.min.js" />
        <Script src="/js/counterup.min.js" />
        <Script src="/js/waypoints-sticky.min.js" />
        <Script src="/js/isotope.pkgd.min.js" />
        <Script src="/js/owl.carousel.min.js" />
        <Script src="/js/slick.min.js" />
        <Script src="/js/theia-sticky-sidebar.js" />
        <Script src="/js/m-custom-scrollbar.min.js" />
        <Script src="/js/dropzone.js" />
        <Script src="/js/bootstrap4-toggle.min.js" />
        <Script src="/js/jquery.dataTables.min.js" />
        <Script src="/js/dataTables.bootstrap4.min.js" />
        <Script src="/js/custom.js" />
        <Script src="/js/lc_lightbox.lite.js" />
        <Script src="/js/bootstrap-slider.min.js" />
      </body>
    </html>
  );
}
